### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by youngvanda** [TheNittam/RPOscanner#1]
Hello.
I'm getting this error in the picture.
I'd be glad to help me.

![image](https://user-images.githubusercontent.com/45789216/129483599-f522e4a5-a8e2-45c1-8062-cd31e3dc5cc3.png)

**Comment by Terxeno** [comment]
Change to
`assert __file__ != sys.argv[0]`

**Comment by ghost** [comment]
thanks @Terxeno  ~it is work now
